### PR TITLE
Prohibit ghost blocks from getting pulled by fishing rod

### LINKED ISSUE #51: Ghost blocks can be pulled by fishing rod, and turn into real blocks
## Description (Required)

Ghost blocks are static falling blocks, but they can be pulled by fishing rod, either to the sky or turn into real block if hit other blocks.

## Steps to reproduce the Issue (Required)

1. Place a ghost block.
2. Pull with fishing rod.
3. Ghost block flies~

## Expected behavior (Required)

The block cannot be pulled by fishing rod.

## Server Log / Error Report

N/A

## Environment (Required)

 - Minecraft Version: paper-1.18.1-216
 - CS-CoreLib Version: N/A
 - Slimefun Version: dev - 1006
 - Plugin Version: dev - 53

### PR DESCRIPTION
**Pull request by ybw0014**
Fixes #51

### CODE REVIEW

File: src/main/java/me/gallowsdove/foxymachines/listeners/GhostBlockListener.java [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+
+public class GhostBlockListener implements Listener {
+    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
+    private void onHitByFishingRod(PlayerFishEvent e) {
+        if (!(e.getCaught() instanceof FallingBlock b)) {
+            return;
+        }
+        if (b.getPersistentDataContainer().has(GhostBlock.KEY, PersistentDataType.STRING)) {
+            e.setCancelled(true);
+        }
```
Comment (GallowsDove) [inline src/main/java/me/gallowsdove/foxymachines/listeners/GhostBlockListener.java]: Maybe just merge this into single if statement? I find it weird to use return before just a single if.

**Review by GallowsDove — CHANGES_REQUESTED** [review]

**Comment by GallowsDove** [comment]
Maybe I'm just petty. Otherwise it's of course good, thanks ^^
